<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StorePrecalificacionRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        //'phone' => 'required|regex:/^\+?[0-9]{1,3}?[-. ]?[0-9]{1,4}[-. ]?[0-9]{1,4}[-. ]?[0-9]{1,9}$/',
        return [
            'co_idioma' => 'required|integer',
            'co_metodo_pago_proyecto' => 'required|integer',
            'nu_precio_total' => 'required|numeric|min:0',
            'nu_down_payment' => 'nullable|numeric|min:0',
            'tx_metodo_pago' => 'nullable|string|max:255',
            'co_metodo_down_payment' => 'nullable|integer',
            'nu_precio_financiado' => 'nullable|numeric|min:0',
            'bo_co_signer' => 'nullable|string',
            'co_producto' => 'nullable|integer',
            'nu_cantidad_adultos' => 'required|integer|min:0',
            'nu_cantidad_ninos' => 'required|integer|min:0',
            'co_tipo_agua' => 'required|integer',
            'fe_instalacion' => 'required|date',
            'tx_hora_instalacion' => 'required|string',
            'co_estatus_aplicacion' => 'nullable|int',

            // Datos del cliente 1 (Principal)
            'tx_primer_nombre_c1' => 'required|string|max:255',
            'tx_inicial_segundo_c1' => 'nullable|string|max:1',
            'tx_apellido_c1' => 'required|string|max:255',
            'tx_telefono_c1' => 'required|string|max:20',
            'tx_email_c1' => 'required|email|max:255',
            //'confirm_email' => 'required|email|same:tx_email_c1',
            'tx_direccion1_c1' => 'required|string|max:255',
            'tx_direccion2_c1' => 'nullable|string|max:255',
            'tx_ciudad_c1' => 'required|string|min:3|max:255',
            'co_estado_c1' => 'required|integer',
            'tx_zip_c1' => 'required|string|max:255',
            'fe_fecha_nacimiento_c1' => 'required|date',
            'tx_social_security_number_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|digits:9',
            'tx_licencia_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',
            'fe_vencimto_licencia_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|date',
            'tx_url_img_photoid_c1' => 'required|image|min:1|max:30720|mimes:jpeg,jpg,gif,png,webp',

            // Información laboral cliente 1
            'tx_nombre_trabajo_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',
            'nu_tiempo_trabajo_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|integer|min:0',
            'tx_puesto_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',
            'nu_salario_mensual_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|numeric|min:0',
            'tx_tlf_trab_c1' => 'nullable|string|max:20',
            'tx_direc1_trab_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',
            'tx_direc2_trab_c1' => 'nullable|string|max:255',
            'tx_ciudad_trab_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|min:3|max:255',
            'co_estado_trab_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|integer',
            'tx_zip_trab_c1' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:10',            
            'nu_ingresos_alter_c1' => 'nullable|numeric|min:0',

            // Datos del cliente 2 (Co-aplicante)
            'tx_relacion_c2_con_c1' => 'nullable|required_if_accepted:bo_co_signer|string|max:255',
            'tx_primer_nombre_c2' => 'nullable|required_if_accepted:bo_co_signer|string|max:255',
            'tx_inicial_segundo_c2' => 'nullable|string|max:1',
            'tx_apellido_c2' => 'nullable|required_if_accepted:bo_co_signer|string|max:255',
            'tx_telefono_c2' => 'nullable|required_if_accepted:bo_co_signer|string|max:20',
            'tx_email_c2' => 'nullable|required_if_accepted:bo_co_signer|email|max:255',
            //'confirm_email_c2' => 'nullable|required_if_accepted:bo_co_signer|email|max:255|same:tx_email_c2',
            'fe_fecha_nacimiento_c2' => 'nullable|required_if_accepted:bo_co_signer|date',
            'tx_social_security_number_c2' => 'nullable|required_if_accepted:bo_co_signer|digits:9',
            'tx_licencia_c2' => 'nullable|required_if_accepted:bo_co_signer|string|max:255',
            'fe_vencimto_licencia_c2' => 'nullable|required_if_accepted:bo_co_signer|date',
            'tx_url_img_photoid_c2' => 'nullable|required_if_accepted:bo_co_signer|image|min:1|max:30720|mimes:jpeg,jpg,gif,png,webp',

            // Información laboral cliente 2
            'tx_nombre_trabajo_c2' => 'nullable|required_if_accepted:bo_co_signer|string|max:255',
            'nu_tiempo_trabajo_c2' => 'nullable|required_if_accepted:bo_co_signer|integer|min:0',
            'tx_puesto_c2' => 'nullable|required_if_accepted:bo_co_signer|string|max:255',
            'nu_salario_mensual_c2' => 'nullable|required_if_accepted:bo_co_signer|numeric|min:0',
            'tx_direc1_trab_c2' => 'nullable|string|max:255',
            'tx_direc2_trab_c2' => 'nullable|string|max:255',
            'tx_ciudad_trab_c2' => 'nullable|string|max:255',
            'co_estado_trab_c2' => 'nullable|integer',
            'tx_zip_trab_c2' => 'nullable|string|max:10',
            'tx_tlf_trab_c2' => 'nullable|string|max:20',
            'nu_ingresos_alter_c2' => 'nullable|numeric|min:0',

            // Información de hipoteca
            'tx_hipoteca_estatus' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',
            'tx_hipoteca_company' => 'nullable|string|max:255',
            'nu_hipoteca_renta' => 'nullable|required_if:co_metodo_pago_proyecto,2|numeric|min:0',
            'nu_hipoteca_tiempo' => 'nullable|required_if:co_metodo_pago_proyecto,2|integer|min:0',

            // Referencias
            'tx_ref1_nombre' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',
            'tx_ref1_telefono' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:20',
            'tx_ref1_relacion' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',
            'tx_ref2_nombre' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',
            'tx_ref2_telefono' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:20',
            'tx_ref2_relacion' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',

            // Firmas
            'tx_url_img_signature_c1' => 'required|string',
            'tx_url_img_signature_c2' => 'nullable|required_if_accepted:bo_co_signer|string',         

            // Owner Setter cliente 1
            'co_qb_setter' => 'required|integer',
            'co_qb_owner' => 'required|integer',
            'co_cliente' => 'required|integer',
            'tx_url_orden_trabajo' => 'nullable|string',
            'tx_hipoteca_tiempo' => 'nullable|required_if:co_metodo_pago_proyecto,2|string|max:255',

            //Informacion bancaria
            'tx_nombre_banco' => 'nullable|string|max:255',
            'tx_numero_cuenta' => 'nullable|string|max:17',
            'tx_numero_ruta' => 'nullable|digits:9',
            'co_tipo_cuenta' => 'nullable|integer',
            'tx_titular_cuenta' => 'nullable|string|max:255',
        ];
    }

    public function messages()
    {
        return [
            'co_idioma.required' => 'El idioma es requerido.',
            'co_metodo_pago_proyecto.required' => 'El método de pago del proyecto es requerido.',
            'nu_precio_total.required' => 'El precio total es requerido.',
            'nu_precio_total.numeric' => 'El precio total debe ser una cantidad numérica.',
            'nu_precio_total.min' => 'El precio total debe ser mayor a 0.',
            'nu_down_payment.required' => 'El pago inicial es requerido.',
            'nu_down_payment.numeric' => 'El pago inicial debe ser una cantidad numérica.',
            'nu_down_payment.min' => 'El pago inicial debe ser al menos 0.',
            'tx_metodo_pago.string' => 'El método de pago debe ser una cadena de texto.',
            'tx_metodo_pago.max' => 'El método de pago no puede exceder 255 caracteres.',
            'nu_precio_financiado.required' => 'El precio financiado es requerido.',
            'nu_precio_financiado.numeric' => 'El precio financiado debe ser un número.',
            'nu_precio_financiado.min' => 'El precio financiado debe ser al menos 0.',
            'nu_cantidad_adultos.required' => 'La cantidad de adultos es requerida.',
            'nu_cantidad_adultos.integer' => 'La cantidad de adultos debe ser un número entero.',
            'nu_cantidad_adultos.min' => 'La cantidad de adultos no puede ser menor que 0.',
            'nu_cantidad_ninos.required' => 'La cantidad de niños es requerida.',
            'nu_cantidad_ninos.integer' => 'La cantidad de niños debe ser un número entero.',
            'nu_cantidad_ninos.min' => 'La cantidad de niños no puede ser menor que 0.',
            'co_tipo_agua.required' => 'El tipo de agua es requerido.',
            'fe_instalacion.required' => 'La fecha de instalación es requerida.',
            'fe_instalacion.date' => 'La fecha de instalación debe ser una fecha válida.',
            'tx_hora_instalacion.required' => 'La hora de instalación es requerida.',
            'tx_hora_instalacion.string' => 'La hora de instalación debe ser una cadena de texto.',
            'tx_primer_nombre_c1.required' => 'El primer nombre del cliente es requerido.',
            'tx_apellido_c1.required' => 'El apellido del cliente es requerido.',
            'tx_telefono_c1.required' => 'El teléfono del cliente es requerido.',
            'tx_email_c1.required' => 'El email del cliente es requerido.',
            'tx_email_c1.email' => 'El email debe ser una dirección válida.',
            'tx_direccion1_c1.required' => 'La dirección del cliente es requerida.',
            'tx_direccion1_c1.max' => 'La dirección del cliente debe tener maximo 255 caracteres.',
            'tx_ciudad_c1.required' => 'La ciudad del cliente es requerida.',
            'tx_ciudad_c1.min' => 'La ciudad del cliente debe tener minimo 3 caracteres.',
            'tx_ciudad_c1.max' => 'La ciudad del cliente debe tener maximo 255 caracteres.',
            'co_estado_c1.required' => 'El estado del cliente es requerido.',
            'co_estado_c1.integer' => 'El estado del cliente debe ser un número entero.',
            'tx_zip_c1.required' => 'El código postal del cliente es requerido.',
            'tx_zip_c1.max' => 'El código postal del cliente debe ser maximo 255 caracteres.',
            'fe_fecha_nacimiento_c1.required' => 'La fecha de nacimiento del cliente es requerida.',
            'fe_fecha_nacimiento_c1.date' => 'La fecha de nacimiento del cliente debe ser una fecha válida.',
            'tx_social_security_number_c1.required_if' => 'El número de seguro social es requerido si el método de pago es Finaciado.',
            'tx_social_security_number_c1.digits' => 'El número de seguro social debe ser un valor con 9 digitos.',
            'tx_licencia_c1.required_if' => 'La licencia es requerida si el método de pago es Financiado.',
            'tx_licencia_c1.string' => 'La licencia debe ser una cadena de texto.',
            'tx_licencia_c1.max' => 'La licencia debe tener máximo 250 caracteres.',
            'fe_vencimto_licencia_c1.required_if' => 'La fecha de vencimiento de la licencia es requerida si el método de pago es Financiado.',
            'fe_vencimto_licencia_c1.date' => 'La fecha de vencimiento de la licencia debe ser una fecha válida.',
            'tx_url_img_photoid_c1.required' => 'La imagen de identificación es requerida.',
            'tx_nombre_trabajo_c1.required_if' => 'El nombre del trabajo es requerido si el método de pago es Financiado.',
            'nu_tiempo_trabajo_c1.required_if' => 'El tiempo de trabajo es requerido si el método de pago es Financiado.',
            'tx_puesto_c1.required_if' => 'El puesto es requerido si el método de pago es Financiado.',
            'nu_salario_mensual_c1.required_if' => 'El salario mensual es requerido si el método de pago es Financiado.',
            'tx_relacion_c2_con_c1.required_if_accepted' => 'La relación con el cliente es requerida.',
            'tx_primer_nombre_c2.required_if_accepted' => 'El primer nombre del co-firmante es requerido.',
            'tx_apellido_c2.required_if_accepted' => 'El apellido del co-firmante es requerido.',
            'tx_telefono_c2.required_if_accepted' => 'El teléfono del co-firmante es requerido.',
            'tx_email_c2.required_if_accepted' => 'El email del co-firmante es requerido.',
            'fe_fecha_nacimiento_c2.required_if_accepted' => 'La fecha de nacimiento del co-firmante es requerida.',
            'fe_fecha_nacimiento_c2.date' => 'La fecha de nacimiento del co-firmante debe ser una fecha válida.',
            'tx_social_security_number_c2.required_if_accepted' => 'El número de seguro social del co-firmante es requerido.',
            'tx_social_security_number_c2.digits' => 'El número de seguro social del co-firmante debe tener 9 digitos.',
            'tx_licencia_c2.required_if_accepted' => 'La licencia del co-firmante es requerida.',
            'tx_licencia_c2.string' => 'La licencia del co-firmante es una cadena de texto.',
            'tx_licencia_c2.max' => 'La licencia del co-firmante debe tener máximo 250 caracteres.',
            'fe_vencimto_licencia_c2.required_if_accepted' => 'La fecha de vencimiento de la licencia del co-firmante es requerida.',
            'fe_vencimto_licencia_c2.date' => 'La fecha de vencimiento de la licencia del co-firmante debe ser una fecha válida.',
            'tx_url_img_photoid_c2.required_if_accepted' => 'La imagen de identificación del co-firmante es requerida.',
            'tx_hipoteca_estatus.required_if' => 'El estatus de la hipoteca es requerido si el método de pago es Financiado.',
            'tx_hipoteca_company.string' => 'El nombre de la compañía hipotecaria debe ser texto.',
            'tx_hipoteca_company.max' => 'El nombre de la compañía hipotecaria no debe exceder los 255 caracteres.',
            'nu_hipoteca_renta.required_if' => 'La renta de la hipoteca es requerida si el método de pago es Financiado.',
            'nu_hipoteca_tiempo.required_if' => 'El tiempo de la hipoteca es requerido si el método de pago es Financiado.',
            'tx_ref1_nombre.required_if' => 'El nombre de la referencia 1 es requerido si el método de pago es Financiado.',
            'tx_ref1_telefono.required_if' => 'El teléfono de la referencia 1 es requerido si el método de pago es Financiado.',
            'tx_ref1_relacion.required_if' => 'La relación de la referencia 1 es requerida si el método de pago es Financiado.',
            'tx_ref2_nombre.required_if' => 'El nombre de la referencia 2 es requerido si el método de pago es Financiado.',
            'tx_ref2_telefono.required_if' => 'El teléfono de la referencia 2 es requerido si el método de pago es Financiado.',
            'tx_ref2_relacion.required_if' => 'La relación de la referencia 2 es requerida si el método de pago es Financiado.',
            'tx_url_img_signature_c1.string' => 'La firma del cliente 1 debe ser una cadena de texto.',
            'tx_url_img_signature_c2.string' => 'La firma del cliente 2 debe ser una cadena de texto.',
            'co_qb_setter.required' => 'El analista es requerido.',
            'co_qb_owner.required' => 'El propietario es requerido.',
            'co_cliente.required' => 'El cliente es requerido.',
            'confirm_email_c2.required_if_accepted' => 'El campo de confirmación de email es requerido para el co-firmante.',
            'confirm_email_c2.email' => 'El campo de confirmación de email del co-firmante debe ser una dirección de correo electrónico válida.',
            'confirm_email_c2.max' => 'El campo de confirmación de email del co-firmante no puede exceder los 255 caracteres.',
            'confirm_email_c2.same' => 'El campo de confirmación de email debe coincidir con el email proporcionado.',
            'confirm_email.required' => 'El campo de confirmación de email es requerido.',
            'confirm_email.email' => 'El campo de confirmación de email debe ser una dirección de correo electrónico válida.',
            'confirm_email.same' => 'El campo de confirmación de email debe coincidir con el email proporcionado.',
            'tx_hipoteca_tiempo.required_if' => 'El tiempo de hipoteca es requerido.',
            'nu_tiempo_trabajo_c2.required_if' => 'El tiempo de trabajo del co-firmante es requerido',
            'tx_puesto_c2.required_if' => 'El cargo del trabajo del co-firmante es requerido',
            'tx_numero_ruta.digits' => 'El número de ruta debe tener exactamente 9 dígitos.',            
            'tx_numero_cuenta.max' => 'El número de cuenta debe tener maximo 17 caracteres.',
            'co_tipo_cuenta.integer' => 'El tipo de cuenta debe ser un número entero.',
            'tx_titular_cuenta.string' => 'El titular de la cuenta debe ser una cadena de texto.',
            'tx_titular_cuenta.max' => 'El titular de la cuenta debe tener maximo 255 caracteres.',
        ];
    }
}